name: Test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.407'
      - run: dotnet build
      - run: dotnet test